### ISSUE TITLE
arch: reject full PTY terminal emulator for 0.2.x

### ISSUE THREAD

**Issue by SSobol77** [SSobol77/ecli#88]
# Document that ECLI 0.2.x does not implement a full terminal emulator. F11 is a console panel, not a PTY/xterm replacement.

## Acceptance:
- architecture note added
- docs mention F11 PySH Console Panel direction
- full PTY terminal is explicitly out of scope
- no VMLab scope added

**Comment by SSobol77** [comment]
Closed by architecture decision: full PTY terminal emulator is rejected for ECLI 0.2.x; F11 direction is PySH Console Panel. Follow-up implementation continues in #89 and regression coverage in #90.
